version: "3.8"

networks:
  laravel:
    name: laravel

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - laravel
  php:
    image: php:7.4.12-fpm-alpine
    container_name: php
    networks:
      - laravel
  mysql:
    image: mysql:5.7.32
    container_name: mysql
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel
